config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from notes import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include("notes.urls")),
    path('users/', include("users.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

notes/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.note_list_view,name="home"),
    path('finished/<int:id>/',views.finished_item,name="finished"),
    path('undo/<int:id>/',views.undo_item,name="undo"),
    path('delete/<int:id>/',views.delete_item,name="delete"),
]

users/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("signup/",views.signup,name="signup"),
    path("login/",views.signin,name="login"),
    path("logout/",views.signout,name="logout"),
]

notes/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.


class Note(models.Model):
    LABEL_CHOICES = (
        ('P', 'primary'),
        ('SE', 'secondary'),
        ('S', 'success'),
        ('D', 'danger'),
        ('W', 'warning'),
        ('I', 'info'),
        ('L', 'light'),
        ('DA', 'dark'),
    )
    user =models.ForeignKey(User,on_delete=models.CASCADE,related_name="todos")
    title = models.CharField(max_length=200)
    due_date = models.DateTimeField()
    label = models.CharField(max_length=2, choices=LABEL_CHOICES, default="P")
    finished = models.BooleanField(default=False)
    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

notes/forms.py
from django import forms
from django.forms import fields
from . import models
class NoteModelForm(forms.ModelForm):
    class Meta:
        model = models.Note
        fields = ('title','due_date','label')

notes/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from . import models
from .forms import NoteModelForm
# Create your views here.


@login_required
def note_list_view(request):
    form = NoteModelForm()
    if request.method == "POST":
        form = NoteModelForm(request.POST)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.user = request.user
            todo.save()
            return redirect("home")
    user = request.user
    todos = user.todos.all()
    todo_list = todos.filter(finished=False)
    finished_list = todos.filter(finished=True)
    return render(request, "notes/note_list.html", context={"todo_list": todo_list, "finished_list": finished_list, "form": form})


@login_required
def finished_item(request, id):
    item = models.Note.objects.get(pk=id)
    item.finished = True
    item.save()
    return redirect("home")


@login_required
def undo_item(request, id):
    item = models.Note.objects.get(pk=id)
    item.finished = False
    item.save()
    return redirect("home")


@login_required
def delete_item(request, id):
    item = models.Note.objects.get(pk=id)
    item.delete()
    return redirect("home")

users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
# Create your views here.


def signup(request):
    if request.user.is_authenticated:
        return redirect("home")
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password1")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home")
        else:
            return render(request, "users/user_signup.html", context={"signup_form": form})
    else:
        form = UserCreationForm()
        return render(request, "users/user_signup.html", context={"signup_form": form})


def signin(request):
    if request.user.is_authenticated:
        return redirect("home")
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user=user)
            return redirect("home")
    else:
        form = AuthenticationForm()
        return render(request, "users/user_login.html", context={"login_form": form})


def signout(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect("login")
    else:
        return redirect("login")

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Django Notes</title>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
 </head>
  <body>
  {%if request.user.is_authenticated%}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Django-Todo App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item mr-6">
        <a class="nav-link bg-danger font-weight-bold text-white" href="{% url 'logout' %}" style="font-size:20px;" >Logout</a>
      </li>
    </ul>
  </div>
</nav>
{% endif %}
<main role="main" class="container">
{% block content %}
{% endblock content %}

</main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

templates/note_list.html
{% extends 'base.html' %}

{% block content %}
<style>
h4{
    position: relative;
}
.icons{
    position: absolute;
    right:5px;
}
</style>
    <div class="text-center mt-5">
        <h2>To-Do List
         <a  data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
            <i class="fas fa-plus fa-sm"></i>
        </a>
        </h2>
    </div>
    <hr/>



        <div class="collapse" id="collapseExample">
        <div class="card card-body">
                 <div class="container mb-5">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_title">Title</label>
                            {{form.title}}
                        </div>
                        <div class="form-group">
                            <label for="id_due_date">Due Date(yyyy-mm-dd)</label>
                            {{form.due_date}}
                        </div>
                        <div class="form-group form-check">
                            <label for="id_label">Label</label>
                            {{form.label}}
                        </div>
                        <button class="btn btn-primary" type="submit">create</button>
                    </form>
             </div>
        </div>
        </div>






    <div class="row">
        {% for note in todo_list %}
        <div class="col-12 mb-3">
           {% include "note_snippet.html" with note=note %}
        </div>
        {% endfor %}
    </div>
    <div class="text-center mt-5">
        <h2>Finished List</h2>
    </div>
    <hr/>
    <div class="row">
        {% for note in finished_list %}
        <div class="col-12 mb-3">
            {% include "note_snippet.html" with note=note %}
        </div>
        {% endfor %}
    </div>
{% endblock content %}

templates/notes/note_list.html
{% extends 'base.html' %}

{% block content %}
{% if request.user.is_authenticated %}
<style>
h4{
    position: relative;
}
.icons{
    position: absolute;
    right:5px;
}
</style>
    <div class="text-center mt-5">
        <h2>To-Do List
         <a  data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
            <i class="fas fa-plus fa-sm"></i>
        </a>
        </h2>
    </div>
    <hr/>



        <div class="collapse" id="collapseExample">
        <div class="card card-body">
                 <div class="container mb-5">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_title">Title</label>
                            {{form.title}}
                        </div>
                        <div class="form-group">
                            <label for="id_due_date">Due Date(yyyy-mm-dd)</label>
                            {{form.due_date}}
                        </div>
                        <div class="form-group form-check">
                            <label for="id_label">Label</label>
                            {{form.label}}
                        </div>
                        <button class="btn btn-primary" type="submit">create</button>
                    </form>
             </div>
        </div>
        </div>






    <div class="row">
        {% for note in todo_list %}
        <div class="col-12 mb-3">
           {% include "notes/note_snippet.html" with note=note %}
        </div>
        {% endfor %}
    </div>
    <div class="text-center mt-5">
        <h2>Finished List</h2>
    </div>
    <hr/>
    <div class="row">
        {% for note in finished_list %}
        <div class="col-12 mb-3">
            {% include "notes/note_snippet.html" with note=note %}
        </div>
        {% endfor %}
    </div>
  {% endif %}  
{% endblock content %}

templates/notes/note_snippet.html
 <div class="card">
        <div class="card-body">
            <h4 {% if note.finished %} style="text-decoration:line-through;" {% endif %}>{{note.title}}
                <span class="badge badge-{{ note.get_label_display }}">{{note.due_date}}</span>
            <span class="icons">
            {% if note.finished is not True %}
            <a href="{% url 'finished' note.id %}"><i class="fas fa-check"></i></a>
            {% else %}
            <a href="{% url 'undo' note.id %}"><i class="fas fa-times"></i></a>
            {% endif %}
            <a href="{% url 'delete' note.id %}"><i class="fas fa-trash" style="color:red;margin-left:10px;"></i></a>
            </span>
            </h4>
        </div>
 </div>

templates/users/user_login.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="post" class="mt-5">
  {% csrf_token %}
  <div class="form-group ">
    <label for="id_username" class="mr-2 font-weight-normal" style="font-size:25px;">username:</label>
   {{login_form.username}}
  </div>
  <div class="form-group">
    <label for="id_password" class="mr-2 font-weight-normal" style="font-size:25px;">password:</label>
    {{login_form.password}}
  </div>
  <button type="submit" class="btn btn-primary">Log in</button>
</form>
<div class="mt-3">
  <span>Don't have an account <a href="{% url 'signup' %}">click here</a></span>
</div>
{% endblock content %}

templates/users/user_signup.html
{% extends 'base.html' %}
{% block content %}

<form action="" method="post" class="mt-5">
  {% csrf_token %}
  <div class="form-group ">
    <label for="id_username" class="mr-2 font-weight-normal" style="font-size:25px;">username:</label>
   {{signup_form.username}}
  </div>
  <div class="form-group">
    <label for="id_password1" class="mr-2 font-weight-normal" style="font-size:25px;">password:</label>
    {{signup_form.password1}}
  </div>
   <div class="form-group">
    <label for="id_password2" class="mr-2 font-weight-normal" style="font-size:25px;">confirm password:</label>
    {{signup_form.password2}}
  </div>
  <button type="submit" class="btn btn-primary">Sign up</button>
</form>
<div class="mt-3">
  <span>Already have an account <a href="{% url 'login' %}">click here</a></span>
</div>
{% endblock content %}